[[main]]
  name       = "Services"
  url        = "/services/"
  weight     = 1
  [main.params]
    highlight = true
[[main]]
  name   = "Consulting"
  url    = "/consulting/"
  weight = 2
[[main]]
  name   = "Projects"
  url    = "/projects/"
  weight = 3
[[main]]
  name   = "Blog"
  url    = "/blog/"
  weight = 4
[[main]]
  name   = "About"
  url    = "/about/"
  weight = 5
